name: skypeclone
description: Skype clone - Names says it all

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # For making request to firestore database
  cloud_firestore: ^0.13.5

  #permissions handling
  permission_handler: 3.0.0

  # For handling authentication via firebase
  firebase_auth: ^0.16.0

  # For handling google sign in
  google_sign_in: ^4.4.4

  #for Skype like outline icons
  material_design_icons_flutter: ^4.0.5145

  #for shimmer effect
  shimmer: ^1.1.1

  # Emojies
  emoji_picker: ^0.1.0

  # image_picker
  image_picker: ^0.6.6+1

  #provider state management
  provider: ^4.0.3

  #firebase storage for storing images and stuffs
  firebase_storage: ^3.1.5

  #for using paths in apps
  path_provider: ^1.6.8

  #for caching image for great user experience
  cached_network_image: ^2.2.0+1

  #Video calling engine
  agora_rtc_engine: ^1.0.8

  #Local Storage db
  hive: ^1.4.1+1
  sqflite: ^1.3.0+1

  #intl for formatting
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - playstore.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
